# Generated by Django 4.0.6 on 2022-09-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话号码')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('education_condition', models.SmallIntegerField(choices=[(1, '未上过学'), (2, '小学'), (3, '初中'), (4, '高中'), (5, '大学及以上')], verbose_name='文化程度')),
                ('reside', models.SmallIntegerField(choices=[(1, '独居'), (2, '双老居住'), (3, '子女同住'), (4, '农村幸福互助院'), (5, '其他养老机构')], verbose_name='居住情况')),
                ('labour', models.SmallIntegerField(choices=[(1, '仍工作/干农活'), (0, '不工作/不干农活')], verbose_name='劳动情况')),
                ('health', models.SmallIntegerField(choices=[(1, '自理'), (2, '半自理'), (3, '失能')], verbose_name='健康状况')),
                ('main_life', models.SmallIntegerField(choices=[(1, '养老金'), (1, '子女赡养'), (1, '社会救助'), (1, '劳动收入'), (1, '其他')], verbose_name='主要生活来源')),
            ],
        ),
    ]
