# Generated by Django 4.0.6 on 2022-09-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_alter_userinfo_main_life'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='education_condition',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='main_life',
            new_name='life',
        ),
    ]
