# Generated by Django 4.0.6 on 2023-03-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0004_alter_userinfo_email_alter_userinfo_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='aitest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('test_info', models.DateTimeField(verbose_name='测试时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('height', models.IntegerField(verbose_name='身高')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='体重')),
                ('birthyear', models.IntegerField(verbose_name='出生年份')),
                ('hosipital_year', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='去医院时间')),
                ('sleep', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='平均睡眠时间')),
                ('work', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='平均睡眠时间')),
                ('emotion', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='近日心情')),
                ('emo_times', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='近一年内情绪失控次数')),
                ('education', models.SmallIntegerField(choices=[(1, '未上过学'), (2, '小学'), (3, '初中'), (4, '高中'), (5, '大学及以上')], verbose_name='文化程度')),
                ('reside', models.SmallIntegerField(choices=[(1, '独居'), (2, '双老居住'), (3, '子女同住'), (4, '农村幸福互助院'), (5, '其他养老机构')], verbose_name='居住情况')),
                ('life', models.SmallIntegerField(choices=[(1, '养老金'), (2, '子女赡养'), (3, '社会救助'), (4, '劳动收入'), (5, '其他')], verbose_name='主要生活来源')),
            ],
        ),
    ]
