# Generated by Django 4.0.6 on 2023-03-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0005_aitest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aitest',
            old_name='test_info',
            new_name='test_time',
        ),
    ]
