# Generated by Django 4.0.6 on 2023-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0006_rename_test_info_aitest_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitest',
            name='emotion',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='近日心情（0-100整数）'),
        ),
        migrations.AlterField(
            model_name='aitest',
            name='hosipital_year',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='去医院时间（填年份）'),
        ),
    ]
