# Generated by Django 4.0.6 on 2023-03-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0007_alter_aitest_emotion_alter_aitest_hosipital_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitest',
            name='work',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='平均活动时间'),
        ),
    ]
