# Generated by Django 4.0.6 on 2023-03-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0008_alter_aitest_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitest',
            name='emo_times',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='近一年内情绪失控次数'),
        ),
        migrations.AlterField(
            model_name='aitest',
            name='emotion',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='近日心情（0-100整数）'),
        ),
        migrations.AlterField(
            model_name='aitest',
            name='hosipital_year',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='去医院时间（填年份）'),
        ),
        migrations.AlterField(
            model_name='aitest',
            name='sleep',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均睡眠时间'),
        ),
        migrations.AlterField(
            model_name='aitest',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='aitest',
            name='work',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均活动时间'),
        ),
    ]
