# Generated by Django 4.0.6 on 2023-03-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0009_alter_aitest_emo_times_alter_aitest_emotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_time', models.DateTimeField(verbose_name='测试时间')),
                ('score1', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='记忆力')),
                ('score2', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='定向力')),
                ('score3', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='社会活动能力')),
                ('score4', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='问题解决能力')),
                ('score5', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='视空间能力')),
            ],
        ),
    ]
