# Generated by Django 4.0.6 on 2023-03-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0010_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='username',
            field=models.CharField(default='', max_length=16, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='记忆力'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='定向力'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='社会活动能力'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score4',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='问题解决能力'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score5',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='视空间能力'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_time',
            field=models.DateTimeField(default=None, verbose_name='测试时间'),
        ),
    ]
